# Generated by Django 6.0.6 on 2026-06-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_prompt', models.TextField()),
                ('ai_output', models.TextField()),
                ('innovation_score', models.FloatField(null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('context_bundle', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LLMTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(default='single_inference', max_length=100)),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='core.innovationinsight')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='innovationinsight',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.questionnaireresponse'),
        ),
    ]
