# Generated by Django 6.0.6 on 2026-06-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationinsight',
            name='innovation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='innovationinsight',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='core.questionnaireresponse'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.company'),
        ),
    ]
